# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

# Make sure correct packit copr repo is enabled

- name: Select correct copr repo
  ansible.builtin.set_fact:
    copr_repo_enabled: packit-stable
    copr_repo_disabled: packit-dev
  when: source_branch == 'stable'

- name: Select correct copr repo
  ansible.builtin.set_fact:
    copr_repo_enabled: packit-dev
    copr_repo_disabled: packit-stable
  when: source_branch != 'stable'

- name: Enable {{ copr_repo_enabled }} copr repo
  community.general.copr:
    name: packit/{{ copr_repo_enabled }}
    state: enabled

- name: Disable {{ copr_repo_disabled }} copr repo
  community.general.copr:
    name: packit/{{ copr_repo_disabled }}
    state: disabled

# Make sure dnf fails hard instead of silently falling back to the official
# Fedora repos when the {{ copr_repo_enabled }} copr repo is unreachable
- name: Fail the build if {{ copr_repo_enabled }} copr repo is unreachable
  community.general.ini_file:
    path: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:packit:{{ copr_repo_enabled }}.repo
    section: copr:copr.fedorainfracloud.org:packit:{{ copr_repo_enabled }}
    option: skip_if_unavailable
    value: "False"
